### ISSUE TITLE
would you mind sharing test video source?

### ISSUE THREAD

**Issue by flankechen** [maximilianallan/stereo_ptam#1]
notice that the code use local video source 

  mptr1 = new VideoCapture("pelvis.avi");  
    //mptr1 = new VideoCapture("calibration_video.avi");

would you mind sharing it? 
or is this video source consist of left and right image in one source? 

I am trying to build AR things with dual camera setup.

Thanks

**Comment by maximilianallan** [comment]
Sorry, I don't have this video any more. This project is really old! I think this page has some stereo dataset that might be suitable: http://www.mrpt.org/robotics_datasets. I don't really work in this area any more so I don't really have anything suitable to hand.
